---
http_interactions:
- request:
    method: get
    uri: unix:///var/run/docker.sock/v1.8/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.7.6
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Job-Name:
      - info
      Date:
      - Wed, 12 Feb 2014 17:06:43 GMT
      Content-Length:
      - '694'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        {"Containers":40,"Debug":0,"Driver":"devicemapper","DriverStatus":[["Pool Name","docker-8:4-394003-pool"],["Data file","/var/lib/docker/devicemapper/devicemapper/data"],["Metadata file","/var/lib/docker/devicemapper/devicemapper/metadata"],["Data Space Used","582.5 Mb"],["Data Space Total","102400.0 Mb"],["Metadata Space Used","3.4 Mb"],["Metadata Space Total","2048.0 Mb"]],"ExecutionDriver":"lxc-0.9.0","IPv4Forwarding":1,"Images":14,"IndexServerAddress":"https://index.docker.io/v1/","InitPath":"/usr/lib/docker/dockerinit","InitSha1":"c6e2619aa393a45c9d0851ef2740eb0d29368350","KernelVersion":"3.12.9-2-ARCH","MemoryLimit":1,"NEventsListener":440,"NFd":11,"NGoroutines":90,"SwapLimit":0}
    http_version: 
  recorded_at: Wed, 12 Feb 2014 17:06:43 GMT
recorded_with: VCR 2.8.0
