---
http_interactions:
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.8/containers/create
    body:
      encoding: UTF-8
      string: "{\"Cmd\":[\"true\"],\"Image\":\"base\"}"
    headers:
      User-Agent:
      - Swipely/Docker-API 1.7.6
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 12 Feb 2014 18:05:45 GMT
      Content-Length:
      - '90'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        {"Id":"442d2c596cdc0146d3a375cb1bb0ff4b6c6b3e754d6a50687df511f28ff8d925","Warnings":null}
    http_version: 
  recorded_at: Wed, 12 Feb 2014 18:05:45 GMT
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.8/commit?container=442d2c59&container_config=%7B%22Cmd%22%3D%3E%5B%22pwd%22%5D%7D
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.7.6
      Content-Type:
      - text/plain
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 12 Feb 2014 18:05:46 GMT
      Content-Length:
      - '74'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        {"Id":"8bf7ee4e0ceb6cf71d2e6dcd1ba2a810df6f01066e9b3f417bc9d34c12b44089"}
    http_version: 
  recorded_at: Wed, 12 Feb 2014 18:05:46 GMT
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.8/containers/create
    body:
      encoding: UTF-8
      string: "{\"Image\":\"8bf7ee4e0ceb6cf71d2e6dcd1ba2a810df6f01066e9b3f417bc9d34c12b44089\",\"Cmd\":null}"
    headers:
      User-Agent:
      - Swipely/Docker-API 1.7.6
      Content-Type:
      - application/json
  response:
    status:
      code: 500
      message: 
    headers:
      Content-Type:
      - text/plain; charset=utf-8
      Date:
      - Wed, 12 Feb 2014 18:05:46 GMT
      Content-Length:
      - '29'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        create: No command specified
    http_version: 
  recorded_at: Wed, 12 Feb 2014 18:05:46 GMT
recorded_with: VCR 2.8.0
