---
http_interactions:
- request:
    method: get
    uri: unix:///var/run/docker.sock/v1.8/version
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.7.6
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Job-Name:
      - version
      Date:
      - Wed, 12 Feb 2014 17:06:43 GMT
      Content-Length:
      - '122'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        {"Arch":"amd64","GitCommit":"cc3a8c8","GoVersion":"go1.2","KernelVersion":"3.12.9-2-ARCH","Os":"linux","Version":"0.8.0"}
    http_version: 
  recorded_at: Wed, 12 Feb 2014 17:06:43 GMT
recorded_with: VCR 2.8.0
