---
http_interactions:
- request:
    method: get
    uri: unix:///var/run/docker.sock/v1.9/version
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.8.4
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Job-Name:
      - version
      Date:
      - Fri, 28 Feb 2014 21:44:33 GMT
      Content-Length:
      - '126'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        {"Arch":"amd64","GitCommit":"31e08fd","GoVersion":"go1.2","KernelVersion":"3.13.5-1-ARCH","Os":"linux","Version":"0.8.1-dev"}
    http_version: 
  recorded_at: Fri, 28 Feb 2014 21:44:33 GMT
recorded_with: VCR 2.8.0
